/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppRouteImport } from './routes/app'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsWebsearchRouteImport } from './routes/settings/websearch'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsSkillsRouteImport } from './routes/settings/skills'
import { Route as SettingsShortcutRouteImport } from './routes/settings/shortcut'
import { Route as SettingsScheduledTasksRouteImport } from './routes/settings/scheduled-tasks'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider'
import { Route as SettingsOcrRouteImport } from './routes/settings/ocr'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsModelRouteImport } from './routes/settings/model'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as SettingsLocalModelsRouteImport } from './routes/settings/local-models'
import { Route as SettingsFileProcessingRouteImport } from './routes/settings/file-processing'
import { Route as SettingsDependenciesRouteImport } from './routes/settings/dependencies'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsCodeExecutionRouteImport } from './routes/settings/code-execution'
import { Route as SettingsChannelsRouteImport } from './routes/settings/channels'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as AppQuestionnaireRouteImport } from './routes/app/questionnaire'
import { Route as AppPopScienceRouteImport } from './routes/app/pop-science'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppClinicRouteImport } from './routes/app/clinic'
import { Route as SettingsScheduledTasksIndexRouteImport } from './routes/settings/scheduled-tasks.index'
import { Route as SettingsMcpIndexRouteImport } from './routes/settings/mcp.index'
import { Route as SettingsScheduledTasksTaskIdRouteImport } from './routes/settings/scheduled-tasks.$taskId'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp/servers'
import { Route as SettingsMcpNpxSearchRouteImport } from './routes/settings/mcp/npx-search'
import { Route as SettingsMcpMcpInstallRouteImport } from './routes/settings/mcp/mcp-install'
import { Route as SettingsMcpMarketplacesRouteImport } from './routes/settings/mcp/marketplaces'
import { Route as SettingsMcpBuiltinRouteImport } from './routes/settings/mcp/builtin'
import { Route as SettingsMcpSplatRouteImport } from './routes/settings/mcp/$'
import { Route as SettingsMcpSettingsServerIdRouteImport } from './routes/settings/mcp/settings.$serverId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWebsearchRoute = SettingsWebsearchRouteImport.update({
  id: '/websearch',
  path: '/websearch',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutRoute = SettingsShortcutRouteImport.update({
  id: '/shortcut',
  path: '/shortcut',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScheduledTasksRoute = SettingsScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProviderRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOcrRoute = SettingsOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelRoute = SettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLocalModelsRoute = SettingsLocalModelsRouteImport.update({
  id: '/local-models',
  path: '/local-models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFileProcessingRoute = SettingsFileProcessingRouteImport.update({
  id: '/file-processing',
  path: '/file-processing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDependenciesRoute = SettingsDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCodeExecutionRoute = SettingsCodeExecutionRouteImport.update({
  id: '/code-execution',
  path: '/code-execution',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChannelsRoute = SettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const AppQuestionnaireRoute = AppQuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => AppRoute,
} as any)
const AppPopScienceRoute = AppPopScienceRouteImport.update({
  id: '/pop-science',
  path: '/pop-science',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicRoute = AppClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AppRoute,
} as any)
const SettingsScheduledTasksIndexRoute =
  SettingsScheduledTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsScheduledTasksRoute,
  } as any)
const SettingsMcpIndexRoute = SettingsMcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsScheduledTasksTaskIdRoute =
  SettingsScheduledTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => SettingsScheduledTasksRoute,
  } as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpNpxSearchRoute = SettingsMcpNpxSearchRouteImport.update({
  id: '/npx-search',
  path: '/npx-search',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMcpInstallRoute = SettingsMcpMcpInstallRouteImport.update({
  id: '/mcp-install',
  path: '/mcp-install',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMarketplacesRoute = SettingsMcpMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpBuiltinRoute = SettingsMcpBuiltinRouteImport.update({
  id: '/builtin',
  path: '/builtin',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpSplatRoute = SettingsMcpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpSettingsServerIdRoute =
  SettingsMcpSettingsServerIdRouteImport.update({
    id: '/settings/$serverId',
    path: '/settings/$serverId',
    getParentRoute: () => SettingsMcpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/clinic': typeof AppClinicRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/pop-science': typeof AppPopScienceRoute
  '/app/questionnaire': typeof AppQuestionnaireRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/settings/code-execution': typeof SettingsCodeExecutionRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/local-models': typeof SettingsLocalModelsRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/model': typeof SettingsModelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/ocr': typeof SettingsOcrRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRouteWithChildren
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/scheduled-tasks/$taskId': typeof SettingsScheduledTasksTaskIdRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/scheduled-tasks/': typeof SettingsScheduledTasksIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/app/clinic': typeof AppClinicRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/pop-science': typeof AppPopScienceRoute
  '/app/questionnaire': typeof AppQuestionnaireRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/settings/code-execution': typeof SettingsCodeExecutionRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/local-models': typeof SettingsLocalModelsRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/ocr': typeof SettingsOcrRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/scheduled-tasks/$taskId': typeof SettingsScheduledTasksTaskIdRoute
  '/settings/mcp': typeof SettingsMcpIndexRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/clinic': typeof AppClinicRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/pop-science': typeof AppPopScienceRoute
  '/app/questionnaire': typeof AppQuestionnaireRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/settings/code-execution': typeof SettingsCodeExecutionRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/local-models': typeof SettingsLocalModelsRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/model': typeof SettingsModelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/ocr': typeof SettingsOcrRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRouteWithChildren
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/scheduled-tasks/$taskId': typeof SettingsScheduledTasksTaskIdRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/scheduled-tasks/': typeof SettingsScheduledTasksIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/settings'
    | '/app/clinic'
    | '/app/knowledge'
    | '/app/pop-science'
    | '/app/questionnaire'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/code-execution'
    | '/settings/data'
    | '/settings/dependencies'
    | '/settings/file-processing'
    | '/settings/local-models'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/notifications'
    | '/settings/ocr'
    | '/settings/provider'
    | '/settings/scheduled-tasks'
    | '/settings/shortcut'
    | '/settings/skills'
    | '/settings/system'
    | '/settings/usage'
    | '/settings/websearch'
    | '/settings/'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/scheduled-tasks/$taskId'
    | '/settings/mcp/'
    | '/settings/scheduled-tasks/'
    | '/settings/mcp/settings/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/app/clinic'
    | '/app/knowledge'
    | '/app/pop-science'
    | '/app/questionnaire'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/code-execution'
    | '/settings/data'
    | '/settings/dependencies'
    | '/settings/file-processing'
    | '/settings/local-models'
    | '/settings/model'
    | '/settings/notifications'
    | '/settings/ocr'
    | '/settings/provider'
    | '/settings/shortcut'
    | '/settings/skills'
    | '/settings/system'
    | '/settings/usage'
    | '/settings/websearch'
    | '/settings'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/scheduled-tasks/$taskId'
    | '/settings/mcp'
    | '/settings/scheduled-tasks'
    | '/settings/mcp/settings/$serverId'
  id:
    | '__root__'
    | '/app'
    | '/settings'
    | '/app/clinic'
    | '/app/knowledge'
    | '/app/pop-science'
    | '/app/questionnaire'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/code-execution'
    | '/settings/data'
    | '/settings/dependencies'
    | '/settings/file-processing'
    | '/settings/local-models'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/notifications'
    | '/settings/ocr'
    | '/settings/provider'
    | '/settings/scheduled-tasks'
    | '/settings/shortcut'
    | '/settings/skills'
    | '/settings/system'
    | '/settings/usage'
    | '/settings/websearch'
    | '/settings/'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/scheduled-tasks/$taskId'
    | '/settings/mcp/'
    | '/settings/scheduled-tasks/'
    | '/settings/mcp/settings/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/websearch': {
      id: '/settings/websearch'
      path: '/websearch'
      fullPath: '/settings/websearch'
      preLoaderRoute: typeof SettingsWebsearchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcut': {
      id: '/settings/shortcut'
      path: '/shortcut'
      fullPath: '/settings/shortcut'
      preLoaderRoute: typeof SettingsShortcutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scheduled-tasks': {
      id: '/settings/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/settings/scheduled-tasks'
      preLoaderRoute: typeof SettingsScheduledTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ocr': {
      id: '/settings/ocr'
      path: '/ocr'
      fullPath: '/settings/ocr'
      preLoaderRoute: typeof SettingsOcrRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model': {
      id: '/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof SettingsModelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/local-models': {
      id: '/settings/local-models'
      path: '/local-models'
      fullPath: '/settings/local-models'
      preLoaderRoute: typeof SettingsLocalModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/file-processing': {
      id: '/settings/file-processing'
      path: '/file-processing'
      fullPath: '/settings/file-processing'
      preLoaderRoute: typeof SettingsFileProcessingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dependencies': {
      id: '/settings/dependencies'
      path: '/dependencies'
      fullPath: '/settings/dependencies'
      preLoaderRoute: typeof SettingsDependenciesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/code-execution': {
      id: '/settings/code-execution'
      path: '/code-execution'
      fullPath: '/settings/code-execution'
      preLoaderRoute: typeof SettingsCodeExecutionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/channels': {
      id: '/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof SettingsChannelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/questionnaire': {
      id: '/app/questionnaire'
      path: '/questionnaire'
      fullPath: '/app/questionnaire'
      preLoaderRoute: typeof AppQuestionnaireRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pop-science': {
      id: '/app/pop-science'
      path: '/pop-science'
      fullPath: '/app/pop-science'
      preLoaderRoute: typeof AppPopScienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic': {
      id: '/app/clinic'
      path: '/clinic'
      fullPath: '/app/clinic'
      preLoaderRoute: typeof AppClinicRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/scheduled-tasks/': {
      id: '/settings/scheduled-tasks/'
      path: '/'
      fullPath: '/settings/scheduled-tasks/'
      preLoaderRoute: typeof SettingsScheduledTasksIndexRouteImport
      parentRoute: typeof SettingsScheduledTasksRoute
    }
    '/settings/mcp/': {
      id: '/settings/mcp/'
      path: '/'
      fullPath: '/settings/mcp/'
      preLoaderRoute: typeof SettingsMcpIndexRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/scheduled-tasks/$taskId': {
      id: '/settings/scheduled-tasks/$taskId'
      path: '/$taskId'
      fullPath: '/settings/scheduled-tasks/$taskId'
      preLoaderRoute: typeof SettingsScheduledTasksTaskIdRouteImport
      parentRoute: typeof SettingsScheduledTasksRoute
    }
    '/settings/mcp/servers': {
      id: '/settings/mcp/servers'
      path: '/servers'
      fullPath: '/settings/mcp/servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/npx-search': {
      id: '/settings/mcp/npx-search'
      path: '/npx-search'
      fullPath: '/settings/mcp/npx-search'
      preLoaderRoute: typeof SettingsMcpNpxSearchRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/mcp-install': {
      id: '/settings/mcp/mcp-install'
      path: '/mcp-install'
      fullPath: '/settings/mcp/mcp-install'
      preLoaderRoute: typeof SettingsMcpMcpInstallRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/marketplaces': {
      id: '/settings/mcp/marketplaces'
      path: '/marketplaces'
      fullPath: '/settings/mcp/marketplaces'
      preLoaderRoute: typeof SettingsMcpMarketplacesRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/builtin': {
      id: '/settings/mcp/builtin'
      path: '/builtin'
      fullPath: '/settings/mcp/builtin'
      preLoaderRoute: typeof SettingsMcpBuiltinRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/$': {
      id: '/settings/mcp/$'
      path: '/$'
      fullPath: '/settings/mcp/$'
      preLoaderRoute: typeof SettingsMcpSplatRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/settings/$serverId': {
      id: '/settings/mcp/settings/$serverId'
      path: '/settings/$serverId'
      fullPath: '/settings/mcp/settings/$serverId'
      preLoaderRoute: typeof SettingsMcpSettingsServerIdRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
  }
}

interface AppRouteChildren {
  AppClinicRoute: typeof AppClinicRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppPopScienceRoute: typeof AppPopScienceRoute
  AppQuestionnaireRoute: typeof AppQuestionnaireRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClinicRoute: AppClinicRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppPopScienceRoute: AppPopScienceRoute,
  AppQuestionnaireRoute: AppQuestionnaireRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsMcpRouteChildren {
  SettingsMcpSplatRoute: typeof SettingsMcpSplatRoute
  SettingsMcpBuiltinRoute: typeof SettingsMcpBuiltinRoute
  SettingsMcpMarketplacesRoute: typeof SettingsMcpMarketplacesRoute
  SettingsMcpMcpInstallRoute: typeof SettingsMcpMcpInstallRoute
  SettingsMcpNpxSearchRoute: typeof SettingsMcpNpxSearchRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMcpIndexRoute: typeof SettingsMcpIndexRoute
  SettingsMcpSettingsServerIdRoute: typeof SettingsMcpSettingsServerIdRoute
}

const SettingsMcpRouteChildren: SettingsMcpRouteChildren = {
  SettingsMcpSplatRoute: SettingsMcpSplatRoute,
  SettingsMcpBuiltinRoute: SettingsMcpBuiltinRoute,
  SettingsMcpMarketplacesRoute: SettingsMcpMarketplacesRoute,
  SettingsMcpMcpInstallRoute: SettingsMcpMcpInstallRoute,
  SettingsMcpNpxSearchRoute: SettingsMcpNpxSearchRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMcpIndexRoute: SettingsMcpIndexRoute,
  SettingsMcpSettingsServerIdRoute: SettingsMcpSettingsServerIdRoute,
}

const SettingsMcpRouteWithChildren = SettingsMcpRoute._addFileChildren(
  SettingsMcpRouteChildren,
)

interface SettingsScheduledTasksRouteChildren {
  SettingsScheduledTasksTaskIdRoute: typeof SettingsScheduledTasksTaskIdRoute
  SettingsScheduledTasksIndexRoute: typeof SettingsScheduledTasksIndexRoute
}

const SettingsScheduledTasksRouteChildren: SettingsScheduledTasksRouteChildren =
  {
    SettingsScheduledTasksTaskIdRoute: SettingsScheduledTasksTaskIdRoute,
    SettingsScheduledTasksIndexRoute: SettingsScheduledTasksIndexRoute,
  }

const SettingsScheduledTasksRouteWithChildren =
  SettingsScheduledTasksRoute._addFileChildren(
    SettingsScheduledTasksRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsChannelsRoute: typeof SettingsChannelsRoute
  SettingsCodeExecutionRoute: typeof SettingsCodeExecutionRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDependenciesRoute: typeof SettingsDependenciesRoute
  SettingsFileProcessingRoute: typeof SettingsFileProcessingRoute
  SettingsLocalModelsRoute: typeof SettingsLocalModelsRoute
  SettingsMcpRoute: typeof SettingsMcpRouteWithChildren
  SettingsModelRoute: typeof SettingsModelRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOcrRoute: typeof SettingsOcrRoute
  SettingsProviderRoute: typeof SettingsProviderRoute
  SettingsScheduledTasksRoute: typeof SettingsScheduledTasksRouteWithChildren
  SettingsShortcutRoute: typeof SettingsShortcutRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsWebsearchRoute: typeof SettingsWebsearchRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsChannelsRoute: SettingsChannelsRoute,
  SettingsCodeExecutionRoute: SettingsCodeExecutionRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDependenciesRoute: SettingsDependenciesRoute,
  SettingsFileProcessingRoute: SettingsFileProcessingRoute,
  SettingsLocalModelsRoute: SettingsLocalModelsRoute,
  SettingsMcpRoute: SettingsMcpRouteWithChildren,
  SettingsModelRoute: SettingsModelRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOcrRoute: SettingsOcrRoute,
  SettingsProviderRoute: SettingsProviderRoute,
  SettingsScheduledTasksRoute: SettingsScheduledTasksRouteWithChildren,
  SettingsShortcutRoute: SettingsShortcutRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsWebsearchRoute: SettingsWebsearchRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
